variable "proxmox_endpoint" {
    description = "Endpoint for communicating with Proxmox"
    type = string
}

variable "proxmox_api_token" {
    description = "API token generated by proxmox for authentication"
    type = string
}

variable "proxmox_username" {
    description = "Username for ssh authentication"
    type = string
}

variable "proxmox_private_ssh_key" {
    description = "Private SSH key for authentication"
    type = string
}

variable "proxmox_virtual_machine_tags" {
  description = "Tags to apply to all virtual machines"
  type        = list(string)
  default     = []
}